---
title: "day19-null"
author: "Kristen A, kkakey"
date: "1/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
```

```{r}
shp <- read_sf("./output-data/wi_blocks.shp", crs=4326)
data <- read_csv("raw-data/DECENNIALSF12010.P1_2021-01-03T164105/DECENNIALSF12010.P1_data_with_overlays_2021-01-03T164055.csv")
```

```{r}
data <- data %>%
  filter(P001001!="Total") %>%
  mutate(P001001 = as.numeric(P001001),
         GEOID10 = str_sub(GEO_ID,-15,-1))

final <- left_join(shp, data, by="GEOID10")
final <- final %>%
  mutate(no_pop_ind = ifelse(P001001==0,1,0))
```


```{r}
ggplot() +
  geom_sf(data=final, aes(fill=as.factor(no_pop_ind)), size=0) +
  scale_fill_manual(values = c("#FFFFFF", "#403233")) +
  theme_void() +
  theme(legend.position = "none",
        text = element_text(family="Noto Serif"),
        plot.title = element_text(hjust = .9, vjust=-17),
        plot.subtitle = element_text(hjust = .9, vjust=-28, size=8)) + 
  ggtitle("Uninhabited Areas of Wisconsin") +
  labs(subtitle = "U.S Census blocks where population reported as zero (2010)") +
  ggsave("plot.png", dpi=2000)
```




